name: build-image
description: Build image action

inputs:
  ROLE_ARN: 
    description: The planeo role arn
    required: true
  REGION:
    description: The region to publish resources in
    required: true
  LANG_TYPE:
    description: Application language type
    required: true
  LANG_VERSION:
    description: Application language version
    required: true
  SERVICE_NAME:
    description: The service name
    required: true
  RUN_COMMAND:
    description: The run command
    required: true
  WEBHOOK_SECRET:
    description: The webhook secret
    required: true
  WEBHOOK_URL:
    description: The webhook url
    required: true

runs:
  using: "composite"
  steps:
    - name: Print environment variables exposed by this action
      uses: FranzDiebold/github-env-vars-action@v2
    - name: Extract branch name
      shell: bash
      run: |
        echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Send webhook request 
      shell: bash
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ inputs.WEBHOOK_SECRET }}" \
          -d '{ "service_name": "${{ inputs.SERVICE_NAME }}", "git_repo": "https://github.com/${{ github.repository }}", "git_branch": "${{ steps.extract_branch.outputs.BRANCH_NAME }}", "image_tag": "${{ env.CI_SHA_SHORT }}", "region": "${{ inputs.REGION }}", "role_arn": "${{ inputs.ROLE_ARN }}", "lang_type": "${{ inputs.LANG_TYPE }}", "lang_version": "${{ inputs.LANG_VERSION }}", "run_command": "${{ inputs.RUN_COMMAND }}", "user_id": "${{ github.actor }}" }' \
          ${{ inputs.WEBHOOK_URL }}
